### ISSUE TITLE
求助一下遇到no module named pyopenpose要怎么办

### ISSUE THREAD

**Issue by Edward609c** [JiageWang/openpose-python-cuda10#11]
我按照您所说的步骤将模型下载好放到对应的位置，并且也把下载的dll文件也放到了3rdparty文件夹中，但是执行main.py的时候报错说Traceback (most recent call last):
  File "G:\Openpose-based-GUI-for-Realtime-Pose-Estimate-and-Action-Recognition-master\main.py", line 17, in <module>
    from custom.openpose_model import OpenposeModel
  File "G:\Openpose-based-GUI-for-Realtime-Pose-Estimate-and-Action-Recognition-master\custom\openpose_model.py", line 13, in <module>
    raise e
  File "G:\Openpose-based-GUI-for-Realtime-Pose-Estimate-and-Action-Recognition-master\custom\openpose_model.py", line 8, in <module>
    import pyopenpose as op
ModuleNotFoundError: No module named 'pyopenpose'
请问怎么解决

**Comment by s1n1o1w** [comment]
首先在自己电脑上安装好openpose，这其中需要用vs来生成解决方案，一般是存放在openpose\build_GPU\python\openpose\Release下面，然后把该目录的pyopenpose.cp37-win_amd64.pyd文件拷过去，我是直接把整个Release目录下的所有文件都拷过去了，免得报错

**Comment by Edward609c** [comment]
> 

我在部署openpose的过程中有什么选项没有设置好，可能是cmake没有设置好，或者是vs编译没有配置好，我是完全按照教程[https://blog.csdn.net/SuiJiangPiaoLiu/article/details/126434521](url)来配置的，不知道为什么gpu版本在vs2019里面生成解决方案都有没有问题，但是不知道为什么测试demo运行的时候报错0x00007FFA8709DD7E (ucrtbase.dll) ，请问您知道这个要怎么解决吗

**Comment by Joseph513shen** [comment]
> > 
> 
> 我在部署openpose的过程中有什么选项没有设置好，可能是cmake没有设置好，或者是vs编译没有配置好，我是完全按照教程[https://blog.csdn.net/SuiJiangPiaoLiu/article/details/126434521](url)来配置的，不知道为什么gpu版本在vs2019里面生成解决方案都有没有问题，但是不知道为什么测试demo运行的时候报错0x00007FFA8709DD7E (ucrtbase.dll) ，请问您知道这个要怎么解决吗

我也遇到了相同的问题，请问你解决了吗？我的理解，有了模型就不需要自己再安装openpose了吧？

**Comment by IRELIAsun** [comment]
有人知道如何解决了吗。ModuleNotFoundError: No module named 'pyopenpose'
Error: OpenPose library could not be found.             Did you enable `BUILD_PYTHON` in CMake and             have this Python script in the right folder?
我是报错这个
